CREATE TABLE Characters (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CampaignID INT,
  Name VARCHAR(255),
  Image VARCHAR(255),
  Player BOOLEAN,
  Background TEXT,
  Favourited BOOLEAN
);

CREATE TABLE Campaign (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255),
  DM VARCHAR(255),
  Background TEXT
);

CREATE TABLE Notes (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ObjectID INT,
  Content TEXT
);

CREATE TABLE Locations (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CampaignID INT,
  Name VARCHAR(255),
  Background TEXT,
  Image VARCHAR(255),
  Favourited BOOLEAN
);
